### PR TITLE
Add namespace to Gradle

### LINKED ISSUE #10: Gradle namespace
A problem occurred configuring project ':better_open_file'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

### PR DESCRIPTION
**Pull request by tenhobi**
Fixes #10

### CODE REVIEW

**Comment by tenhobi** [comment]
Hey @bertoldofonseca, any updates with this? 🙏

**Review by bertoldofonseca — APPROVED** [review]

**Comment by bertoldofonseca** [comment]
I will try to do that during this week

**Comment by tenhobi** [comment]
@bertoldofonseca Hi again, I just want to remind you of the release again, so we can use it in prod without the git reference. 🙏

**Comment by tenhobi** [comment]
Hi @bertoldofonseca, could you release these updates? 🙏

**Comment by bertoldofonseca** [comment]
Hey guys. Sorry for the absence.
I'm not currently working with Flutter, so I don't have a way to test it.
I can publish the new version and wait for your feedback.

**Comment by tenhobi** [comment]
that works for us :) 

we already use this using git, but for the convinience we would rather use released package :)

**Pull request merged**
